# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win_v7.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_SN_Slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_SN_Slider.setGeometry(QtCore.QRect(190, 550, 761, 30))
        self.frame_SN_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_SN_Slider.setObjectName("frame_SN_Slider")
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(0, 520, 1041, 16))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.previous_frame_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.previous_frame_pushButton.setGeometry(QtCore.QRect(90, 540, 31, 23))
        self.previous_frame_pushButton.setObjectName("previous_frame_pushButton")
        self.next_frame_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.next_frame_pushButton.setGeometry(QtCore.QRect(140, 540, 31, 23))
        self.next_frame_pushButton.setObjectName("next_frame_pushButton")
        self.start_stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_stop_pushButton.setGeometry(QtCore.QRect(10, 540, 61, 51))
        self.start_stop_pushButton.setObjectName("start_stop_pushButton")
        self.quit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.quit_pushButton.setGeometry(QtCore.QRect(970, 540, 61, 51))
        self.quit_pushButton.setObjectName("quit_pushButton")
        self.player_groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.player_groupBox_1.setGeometry(QtCore.QRect(10, 0, 500, 520))
        self.player_groupBox_1.setObjectName("player_groupBox_1")
        self.video_player_label_1 = QtWidgets.QLabel(self.player_groupBox_1)
        self.video_player_label_1.setGeometry(QtCore.QRect(10, 30, 480, 480))
        self.video_player_label_1.setStyleSheet("background-color: rgb(70, 52, 52);")
        self.video_player_label_1.setText("")
        self.video_player_label_1.setObjectName("video_player_label_1")
        self.player_groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.player_groupBox_2.setGeometry(QtCore.QRect(530, 0, 500, 520))
        self.player_groupBox_2.setObjectName("player_groupBox_2")
        self.video_player_label_2 = QtWidgets.QLabel(self.player_groupBox_2)
        self.video_player_label_2.setGeometry(QtCore.QRect(10, 30, 480, 480))
        self.video_player_label_2.setStyleSheet("background-color: rgb(70, 52, 52);")
        self.video_player_label_2.setText("")
        self.video_player_label_2.setObjectName("video_player_label_2")
        self.current_all_frames_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.current_all_frames_lineEdit.setGeometry(QtCore.QRect(90, 570, 81, 23))
        self.current_all_frames_lineEdit.setText("")
        self.current_all_frames_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.current_all_frames_lineEdit.setReadOnly(True)
        self.current_all_frames_lineEdit.setObjectName("current_all_frames_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 23))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.menu = QtWidgets.QMenu(self.file_menu)
        self.menu.setObjectName("menu")
        self.tools_menu = QtWidgets.QMenu(self.menubar)
        self.tools_menu.setObjectName("tools_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.open_file_action = QtWidgets.QAction(MainWindow)
        self.open_file_action.setObjectName("open_file_action")
        self.open_mask_action = QtWidgets.QAction(MainWindow)
        self.open_mask_action.setObjectName("open_mask_action")
        self.gen_mask_action = QtWidgets.QAction(MainWindow)
        self.gen_mask_action.setObjectName("gen_mask_action")
        self.quit_sys_action = QtWidgets.QAction(MainWindow)
        self.quit_sys_action.setObjectName("quit_sys_action")
        self.functions_action = QtWidgets.QAction(MainWindow)
        self.functions_action.setObjectName("functions_action")
        self.double_view_action = QtWidgets.QAction(MainWindow)
        self.double_view_action.setObjectName("double_view_action")
        self.gen_mask_action_2 = QtWidgets.QAction(MainWindow)
        self.gen_mask_action_2.setObjectName("gen_mask_action_2")
        self.gen_masks_action = QtWidgets.QAction(MainWindow)
        self.gen_masks_action.setObjectName("gen_masks_action")
        self.save_pictures_action = QtWidgets.QAction(MainWindow)
        self.save_pictures_action.setObjectName("save_pictures_action")
        self.save_video_action = QtWidgets.QAction(MainWindow)
        self.save_video_action.setObjectName("save_video_action")
        self.menu.addAction(self.save_pictures_action)
        self.menu.addAction(self.save_video_action)
        self.file_menu.addAction(self.open_file_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.open_mask_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_sys_action)
        self.tools_menu.addAction(self.functions_action)
        self.tools_menu.addAction(self.gen_masks_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视频智能修复与增强系统"))
        self.previous_frame_pushButton.setText(_translate("MainWindow", "<"))
        self.next_frame_pushButton.setText(_translate("MainWindow", ">"))
        self.start_stop_pushButton.setText(_translate("MainWindow", "开始"))
        self.quit_pushButton.setText(_translate("MainWindow", "停止"))
        self.player_groupBox_1.setTitle(_translate("MainWindow", "原视频"))
        self.player_groupBox_2.setTitle(_translate("MainWindow", "修复 /  增强视频"))
        self.file_menu.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "保存"))
        self.tools_menu.setTitle(_translate("MainWindow", "工具"))
        self.help_menu.setTitle(_translate("MainWindow", "帮助"))
        self.open_file_action.setText(_translate("MainWindow", "视频/视频帧"))
        self.open_mask_action.setText(_translate("MainWindow", "mask"))
        self.gen_mask_action.setText(_translate("MainWindow", "生成mask"))
        self.quit_sys_action.setText(_translate("MainWindow", "退出&(Q)"))
        self.functions_action.setText(_translate("MainWindow", "功能"))
        self.double_view_action.setText(_translate("MainWindow", "双视图(默认)"))
        self.gen_mask_action_2.setText(_translate("MainWindow", "mask生成"))
        self.gen_masks_action.setText(_translate("MainWindow", "mask生成"))
        self.save_pictures_action.setText(_translate("MainWindow", "保存为图片"))
        self.save_video_action.setText(_translate("MainWindow", "保存为视频"))


