# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub2_win_v11.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Mask(object):
    def setupUi(self, Dialog_Mask):
        Dialog_Mask.setObjectName("Dialog_Mask")
        Dialog_Mask.resize(847, 605)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Mask.sizePolicy().hasHeightForWidth())
        Dialog_Mask.setSizePolicy(sizePolicy)
        Dialog_Mask.setMinimumSize(QtCore.QSize(847, 605))
        Dialog_Mask.setMaximumSize(QtCore.QSize(847, 605))
        Dialog_Mask.setStyleSheet("#Dialog_Mask{background-color:rgba(107, 107, 107,99);}\n"
"*{\n"
"    font: bold 12pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);}\n"
"\n"
"\n"
"QSpinBox{\n"
"color: rgb(0, 0, 0);}\n"
"QPushButton{\n"
"    background-color:rgba(120, 120, 120,99);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Dialog_Mask)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.main_canvas = QtWidgets.QLabel(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_canvas.sizePolicy().hasHeightForWidth())
        self.main_canvas.setSizePolicy(sizePolicy)
        self.main_canvas.setMinimumSize(QtCore.QSize(603, 508))
        self.main_canvas.setMaximumSize(QtCore.QSize(603, 508))
        self.main_canvas.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.main_canvas.setText("")
        self.main_canvas.setObjectName("main_canvas")
        self.verticalLayout_6.addWidget(self.main_canvas)
        self.tl_slider = QtWidgets.QSlider(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tl_slider.sizePolicy().hasHeightForWidth())
        self.tl_slider.setSizePolicy(sizePolicy)
        self.tl_slider.setMinimumSize(QtCore.QSize(603, 22))
        self.tl_slider.setMaximumSize(QtCore.QSize(603, 22))
        self.tl_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"  border: 0px solid #bbb;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"  background: rgb(0,150,255);\n"
"  border-radius: 0px;\n"
"  margin-top: 8px;\n"
"  margin-bottom: 9px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"  background: rgb(226, 226, 226);\n"
"  border: 0px solid #777; \n"
"  border-radius: 2px; \n"
"  margin-top: 8px; \n"
"  margin-bottom: 9px; \n"
"}\n"
" \n"
"QSlider::handle:horizontal { \n"
"  background: rgb(255,255,255); \n"
"  border: 1px solid rgba(102,102,102,102); \n"
"  width: 8px; \n"
"  height: 8px; \n"
"  border-radius: 5px; \n"
"  margin-top: 2px; \n"
"  margin-bottom: 2px; \n"
"}\n"
" \n"
"QSlider::handle:horizontal:hover { \n"
"  background: rgb(0,150,255); \n"
"  border: 1px solid rgba(102,102,102,102); \n"
"  border-radius: 5px; \n"
"}\n"
"")
        self.tl_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tl_slider.setObjectName("tl_slider")
        self.verticalLayout_6.addWidget(self.tl_slider)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.play_button = QtWidgets.QPushButton(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMinimumSize(QtCore.QSize(34, 30))
        self.play_button.setMaximumSize(QtCore.QSize(34, 30))
        self.play_button.setStyleSheet("border-image:url(:/bg/run.png);\n"
"background-color: rgba(0,0, 0, 0);\n"
"")
        self.play_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bg/运行.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon)
        self.play_button.setIconSize(QtCore.QSize(30, 30))
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_9.addWidget(self.play_button)
        self.lcd = QtWidgets.QLineEdit(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd.sizePolicy().hasHeightForWidth())
        self.lcd.setSizePolicy(sizePolicy)
        self.lcd.setMinimumSize(QtCore.QSize(239, 33))
        self.lcd.setMaximumSize(QtCore.QSize(239, 33))
        self.lcd.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd.setReadOnly(True)
        self.lcd.setObjectName("lcd")
        self.horizontalLayout_9.addWidget(self.lcd)
        self.run_button = QtWidgets.QPushButton(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setMinimumSize(QtCore.QSize(50, 27))
        self.run_button.setMaximumSize(QtCore.QSize(50, 27))
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_9.addWidget(self.run_button)
        self.progress = QtWidgets.QProgressBar(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.progress.setMinimumSize(QtCore.QSize(200, 35))
        self.progress.setMaximumSize(QtCore.QSize(200, 35))
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.horizontalLayout_9.addWidget(self.progress)
        self.save_button = QtWidgets.QPushButton(Dialog_Mask)
        self.save_button.setMinimumSize(QtCore.QSize(50, 27))
        self.save_button.setMaximumSize(QtCore.QSize(50, 27))
        self.save_button.setIconSize(QtCore.QSize(20, 20))
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_9.addWidget(self.save_button)
        self.horizontalLayout_9.setStretch(3, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.interaction_groupBox = QtWidgets.QGroupBox(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interaction_groupBox.sizePolicy().hasHeightForWidth())
        self.interaction_groupBox.setSizePolicy(sizePolicy)
        self.interaction_groupBox.setMinimumSize(QtCore.QSize(211, 160))
        self.interaction_groupBox.setMaximumSize(QtCore.QSize(211, 160))
        self.interaction_groupBox.setStyleSheet("")
        self.interaction_groupBox.setObjectName("interaction_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.interaction_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_s2m = QtWidgets.QRadioButton(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_s2m.sizePolicy().hasHeightForWidth())
        self.radio_s2m.setSizePolicy(sizePolicy)
        self.radio_s2m.setMinimumSize(QtCore.QSize(89, 31))
        self.radio_s2m.setMaximumSize(QtCore.QSize(89, 31))
        self.radio_s2m.setObjectName("radio_s2m")
        self.horizontalLayout.addWidget(self.radio_s2m)
        self.commit_button = QtWidgets.QPushButton(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commit_button.sizePolicy().hasHeightForWidth())
        self.commit_button.setSizePolicy(sizePolicy)
        self.commit_button.setMinimumSize(QtCore.QSize(89, 27))
        self.commit_button.setMaximumSize(QtCore.QSize(89, 27))
        self.commit_button.setObjectName("commit_button")
        self.horizontalLayout.addWidget(self.commit_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_fbrs = QtWidgets.QRadioButton(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_fbrs.sizePolicy().hasHeightForWidth())
        self.radio_fbrs.setSizePolicy(sizePolicy)
        self.radio_fbrs.setMinimumSize(QtCore.QSize(89, 31))
        self.radio_fbrs.setMaximumSize(QtCore.QSize(89, 31))
        self.radio_fbrs.setObjectName("radio_fbrs")
        self.horizontalLayout_2.addWidget(self.radio_fbrs)
        self.radio_free = QtWidgets.QRadioButton(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_free.sizePolicy().hasHeightForWidth())
        self.radio_free.setSizePolicy(sizePolicy)
        self.radio_free.setMinimumSize(QtCore.QSize(89, 31))
        self.radio_free.setMaximumSize(QtCore.QSize(89, 31))
        self.radio_free.setObjectName("radio_free")
        self.horizontalLayout_2.addWidget(self.radio_free)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.brush_label = QtWidgets.QLabel(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brush_label.sizePolicy().hasHeightForWidth())
        self.brush_label.setSizePolicy(sizePolicy)
        self.brush_label.setMinimumSize(QtCore.QSize(76, 27))
        self.brush_label.setMaximumSize(QtCore.QSize(76, 27))
        self.brush_label.setObjectName("brush_label")
        self.horizontalLayout_3.addWidget(self.brush_label)
        self.brush_slider = QtWidgets.QSlider(self.interaction_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brush_slider.sizePolicy().hasHeightForWidth())
        self.brush_slider.setSizePolicy(sizePolicy)
        self.brush_slider.setMinimumSize(QtCore.QSize(102, 22))
        self.brush_slider.setMaximumSize(QtCore.QSize(102, 22))
        self.brush_slider.setStyleSheet("  \n"
"QSlider::handle:horizontal:hover {\n"
"     background-color:rgb(0, 150, 255);\n"
"\n"
"    border-radius:2px; \n"
"    text-align:center; \n"
"    border:none; \n"
"     }")
        self.brush_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brush_slider.setObjectName("brush_slider")
        self.horizontalLayout_3.addWidget(self.brush_slider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.interaction_groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(102, 72))
        self.groupBox.setMaximumSize(QtCore.QSize(102, 72))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(78, 21))
        self.spinBox.setMaximumSize(QtCore.QSize(78, 21))
        self.spinBox.setStyleSheet("font: 7pt \"微软雅黑\";")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(102, 72))
        self.groupBox_2.setMaximumSize(QtCore.QSize(102, 72))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.combo = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo.sizePolicy().hasHeightForWidth())
        self.combo.setSizePolicy(sizePolicy)
        self.combo.setMinimumSize(QtCore.QSize(78, 21))
        self.combo.setMaximumSize(QtCore.QSize(78, 21))
        self.combo.setStyleSheet("font: 7pt \"微软雅黑\";")
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.verticalLayout_3.addWidget(self.combo)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(211, 149))
        self.groupBox_3.setMaximumSize(QtCore.QSize(211, 149))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimap = QtWidgets.QLabel(self.groupBox_3)
        self.minimap.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimap.sizePolicy().hasHeightForWidth())
        self.minimap.setSizePolicy(sizePolicy)
        self.minimap.setMinimumSize(QtCore.QSize(98, 98))
        self.minimap.setMaximumSize(QtCore.QSize(98, 98))
        self.minimap.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.minimap.setText("")
        self.minimap.setObjectName("minimap")
        self.horizontalLayout_5.addWidget(self.minimap)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.zoom_p_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_p_button.sizePolicy().hasHeightForWidth())
        self.zoom_p_button.setSizePolicy(sizePolicy)
        self.zoom_p_button.setMinimumSize(QtCore.QSize(20, 20))
        self.zoom_p_button.setMaximumSize(QtCore.QSize(20, 20))
        self.zoom_p_button.setStyleSheet("border:none;\n"
"background-color: rgba(0,0, 0, 0);\n"
"font: bold 18pt \"微软雅黑\";\n"
"")
        self.zoom_p_button.setObjectName("zoom_p_button")
        self.verticalLayout_4.addWidget(self.zoom_p_button, 0, QtCore.Qt.AlignHCenter)
        self.zoom_m_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_m_button.sizePolicy().hasHeightForWidth())
        self.zoom_m_button.setSizePolicy(sizePolicy)
        self.zoom_m_button.setMinimumSize(QtCore.QSize(20, 20))
        self.zoom_m_button.setMaximumSize(QtCore.QSize(20, 20))
        self.zoom_m_button.setStyleSheet("border:none;\n"
"background-color: rgba(0,0, 0, 0);\n"
"font: bold 18pt \"微软雅黑\";\n"
"")
        self.zoom_m_button.setObjectName("zoom_m_button")
        self.verticalLayout_4.addWidget(self.zoom_m_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.finish_local_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finish_local_button.sizePolicy().hasHeightForWidth())
        self.finish_local_button.setSizePolicy(sizePolicy)
        self.finish_local_button.setMinimumSize(QtCore.QSize(50, 27))
        self.finish_local_button.setMaximumSize(QtCore.QSize(50, 27))
        self.finish_local_button.setStyleSheet("")
        self.finish_local_button.setObjectName("finish_local_button")
        self.verticalLayout_5.addWidget(self.finish_local_button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(211, 78))
        self.groupBox_4.setMaximumSize(QtCore.QSize(211, 78))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.undo_button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undo_button.sizePolicy().hasHeightForWidth())
        self.undo_button.setSizePolicy(sizePolicy)
        self.undo_button.setMinimumSize(QtCore.QSize(80, 27))
        self.undo_button.setMaximumSize(QtCore.QSize(80, 27))
        self.undo_button.setObjectName("undo_button")
        self.horizontalLayout_8.addWidget(self.undo_button)
        self.reset_button = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMinimumSize(QtCore.QSize(100, 27))
        self.reset_button.setMaximumSize(QtCore.QSize(100, 27))
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_8.addWidget(self.reset_button)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.console = QtWidgets.QPlainTextEdit(Dialog_Mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console.sizePolicy().hasHeightForWidth())
        self.console.setSizePolicy(sizePolicy)
        self.console.setMinimumSize(QtCore.QSize(211, 90))
        self.console.setMaximumSize(QtCore.QSize(211, 90))
        self.console.setObjectName("console")
        self.verticalLayout_7.addWidget(self.console)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)

        self.retranslateUi(Dialog_Mask)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Mask)

    def retranslateUi(self, Dialog_Mask):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Mask.setWindowTitle(_translate("Dialog_Mask", "mask 生成"))
        self.run_button.setText(_translate("Dialog_Mask", "生成"))
        self.save_button.setText(_translate("Dialog_Mask", "保存"))
        self.interaction_groupBox.setTitle(_translate("Dialog_Mask", "交互方式"))
        self.radio_s2m.setText(_translate("Dialog_Mask", "涂鸦"))
        self.commit_button.setText(_translate("Dialog_Mask", "清除"))
        self.radio_fbrs.setText(_translate("Dialog_Mask", "点击"))
        self.radio_free.setText(_translate("Dialog_Mask", "任意"))
        self.brush_label.setText(_translate("Dialog_Mask", " 宽度 : 3"))
        self.groupBox.setTitle(_translate("Dialog_Mask", "目标个数"))
        self.groupBox_2.setTitle(_translate("Dialog_Mask", "亮度"))
        self.combo.setItemText(0, _translate("Dialog_Mask", "正常"))
        self.combo.setItemText(1, _translate("Dialog_Mask", "暗淡"))
        self.combo.setItemText(2, _translate("Dialog_Mask", "明亮"))
        self.groupBox_3.setTitle(_translate("Dialog_Mask", "局部"))
        self.zoom_p_button.setText(_translate("Dialog_Mask", "+"))
        self.zoom_m_button.setText(_translate("Dialog_Mask", "-"))
        self.finish_local_button.setText(_translate("Dialog_Mask", "完成"))
        self.groupBox_4.setTitle(_translate("Dialog_Mask", "撤销"))
        self.undo_button.setText(_translate("Dialog_Mask", "撤销"))
        self.reset_button.setText(_translate("Dialog_Mask", "重置当前帧"))


import images_rc
