# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub2_win_v7.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Mask(object):
    def setupUi(self, Dialog_Mask):
        Dialog_Mask.setObjectName("Dialog_Mask")
        Dialog_Mask.resize(712, 490)
        Dialog_Mask.setStyleSheet("")
        self.interaction_groupBox = QtWidgets.QGroupBox(Dialog_Mask)
        self.interaction_groupBox.setGeometry(QtCore.QRect(520, 10, 181, 111))
        self.interaction_groupBox.setObjectName("interaction_groupBox")
        self.radio_s2m = QtWidgets.QRadioButton(self.interaction_groupBox)
        self.radio_s2m.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.radio_s2m.setObjectName("radio_s2m")
        self.radio_fbrs = QtWidgets.QRadioButton(self.interaction_groupBox)
        self.radio_fbrs.setGeometry(QtCore.QRect(120, 30, 51, 21))
        self.radio_fbrs.setObjectName("radio_fbrs")
        self.radio_free = QtWidgets.QRadioButton(self.interaction_groupBox)
        self.radio_free.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.radio_free.setObjectName("radio_free")
        self.brush_slider = QtWidgets.QSlider(self.interaction_groupBox)
        self.brush_slider.setGeometry(QtCore.QRect(10, 90, 161, 16))
        self.brush_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brush_slider.setObjectName("brush_slider")
        self.brush_label = QtWidgets.QLabel(self.interaction_groupBox)
        self.brush_label.setGeometry(QtCore.QRect(90, 60, 71, 16))
        self.brush_label.setObjectName("brush_label")
        self.commit_button = QtWidgets.QPushButton(self.interaction_groupBox)
        self.commit_button.setGeometry(QtCore.QRect(70, 30, 41, 20))
        self.commit_button.setObjectName("commit_button")
        self.run_button = QtWidgets.QPushButton(Dialog_Mask)
        self.run_button.setGeometry(QtCore.QRect(180, 450, 41, 23))
        self.run_button.setObjectName("run_button")
        self.save_button = QtWidgets.QPushButton(Dialog_Mask)
        self.save_button.setGeometry(QtCore.QRect(470, 450, 31, 23))
        self.save_button.setObjectName("save_button")
        self.progress = QtWidgets.QProgressBar(Dialog_Mask)
        self.progress.setGeometry(QtCore.QRect(230, 450, 231, 23))
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.main_canvas = QtWidgets.QLabel(Dialog_Mask)
        self.main_canvas.setGeometry(QtCore.QRect(10, 10, 500, 400))
        self.main_canvas.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.main_canvas.setObjectName("main_canvas")
        self.tl_slider = QtWidgets.QSlider(Dialog_Mask)
        self.tl_slider.setGeometry(QtCore.QRect(20, 420, 481, 16))
        self.tl_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tl_slider.setObjectName("tl_slider")
        self.lcd = QtWidgets.QLineEdit(Dialog_Mask)
        self.lcd.setGeometry(QtCore.QRect(90, 452, 71, 21))
        self.lcd.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd.setReadOnly(True)
        self.lcd.setObjectName("lcd")
        self.play_button = QtWidgets.QPushButton(Dialog_Mask)
        self.play_button.setGeometry(QtCore.QRect(30, 452, 41, 21))
        self.play_button.setObjectName("play_button")
        self.groupBox = QtWidgets.QGroupBox(Dialog_Mask)
        self.groupBox.setGeometry(QtCore.QRect(520, 130, 81, 61))
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(20, 30, 47, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_Mask)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 130, 81, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.combo = QtWidgets.QComboBox(self.groupBox_2)
        self.combo.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.combo.setObjectName("combo")
        self.combo.addItem("")
        self.combo.addItem("")
        self.combo.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog_Mask)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 190, 181, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.minimap = QtWidgets.QLabel(self.groupBox_3)
        self.minimap.setGeometry(QtCore.QRect(10, 30, 120, 120))
        self.minimap.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.minimap.setText("")
        self.minimap.setObjectName("minimap")
        self.zoom_p_button = QtWidgets.QPushButton(self.groupBox_3)
        self.zoom_p_button.setGeometry(QtCore.QRect(140, 40, 31, 23))
        self.zoom_p_button.setObjectName("zoom_p_button")
        self.zoom_m_button = QtWidgets.QPushButton(self.groupBox_3)
        self.zoom_m_button.setGeometry(QtCore.QRect(140, 70, 31, 23))
        self.zoom_m_button.setObjectName("zoom_m_button")
        self.finish_local_button = QtWidgets.QPushButton(self.groupBox_3)
        self.finish_local_button.setGeometry(QtCore.QRect(140, 120, 31, 23))
        self.finish_local_button.setObjectName("finish_local_button")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog_Mask)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 350, 181, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.undo_button = QtWidgets.QPushButton(self.groupBox_4)
        self.undo_button.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.undo_button.setObjectName("undo_button")
        self.reset_button = QtWidgets.QPushButton(self.groupBox_4)
        self.reset_button.setGeometry(QtCore.QRect(100, 30, 71, 21))
        self.reset_button.setObjectName("reset_button")
        self.console = QtWidgets.QPlainTextEdit(Dialog_Mask)
        self.console.setGeometry(QtCore.QRect(520, 420, 181, 61))
        self.console.setObjectName("console")

        self.retranslateUi(Dialog_Mask)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Mask)

    def retranslateUi(self, Dialog_Mask):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Mask.setWindowTitle(_translate("Dialog_Mask", "mask 生成"))
        self.interaction_groupBox.setTitle(_translate("Dialog_Mask", "交互方式"))
        self.radio_s2m.setText(_translate("Dialog_Mask", "涂鸦"))
        self.radio_fbrs.setText(_translate("Dialog_Mask", "点击"))
        self.radio_free.setText(_translate("Dialog_Mask", "任意"))
        self.brush_label.setText(_translate("Dialog_Mask", " 宽度: 3"))
        self.commit_button.setText(_translate("Dialog_Mask", "清除"))
        self.run_button.setText(_translate("Dialog_Mask", "生成"))
        self.save_button.setText(_translate("Dialog_Mask", "保存"))
        self.main_canvas.setText(_translate("Dialog_Mask", "TextLabel"))
        self.play_button.setText(_translate("Dialog_Mask", "播放"))
        self.groupBox.setTitle(_translate("Dialog_Mask", "目标个数"))
        self.groupBox_2.setTitle(_translate("Dialog_Mask", "亮度"))
        self.combo.setItemText(0, _translate("Dialog_Mask", "正常"))
        self.combo.setItemText(1, _translate("Dialog_Mask", "暗淡"))
        self.combo.setItemText(2, _translate("Dialog_Mask", "明亮"))
        self.groupBox_3.setTitle(_translate("Dialog_Mask", "局部"))
        self.zoom_p_button.setText(_translate("Dialog_Mask", "+"))
        self.zoom_m_button.setText(_translate("Dialog_Mask", "-"))
        self.finish_local_button.setText(_translate("Dialog_Mask", "完成"))
        self.groupBox_4.setTitle(_translate("Dialog_Mask", "撤销"))
        self.undo_button.setText(_translate("Dialog_Mask", "撤销"))
        self.reset_button.setText(_translate("Dialog_Mask", "重置当前帧"))


